name: Concrete

channels:
  - conda-forge
  
dependencies:
  - python=3.9
  - numpy=1.24*
  - numba
  - scipy
  - pandas
  - scikit-image
  - scikit-learn
  - opencv
  - joblib
  - matplotlib-base
  - pystackreg
  - spyder
  - pip
  - pip:
    - napari[all]