name: Concrete-gpu

channels:
  - conda-forge

dependencies:
  - python=3.10
  - numpy=1.24*
  - numba
  - scipy
  - pandas
  - scikit-image
  - opencv
  - scikit-learn
  - joblib
  - matplotlib-base
  - cudatoolkit=11.2
  - cudnn=8.1
  - pystackreg
  - spyder
  - pip
  - pip:
    - bd-tools==0.1.0
    - napari[all]
    - albumentations
    - segmentation-models
    - tensorflow-gpu==2.10